from django.urls import path
from . import views

urlpatterns = [
    path('in', views.inventory_in, name='inventory-in'),
    path('out/sales', views.out_sales, name='out-sales'),
    path('out/inpatient', views.out_inpatient, name='out-inpatient'),
    path('out/inpatient/create', views.out_inpatient_create,
         name='out-inpatient-create'),
    path('out/inpatient/update/status', views.update_inpatient_status,
         name='update-inpatient-status'),
    path('out/inpatient/edit/<int:trans_id>', views.out_inpatient_edit,
         name='out-inpatient-edit'),
    path('out/inpatient/update', views.out_inpatient_update,
         name='out-inpatient-update'),
    path('out/damage', views.out_damage, name='out-damage'),
    path('out/damage/create', views.out_damage_create,
         name='out-damage-create'),
    path('store_stock_data', views.store_stock_data, name='store-stock-data'),
    path('update_stock_data', views.update_stock_data, name='update-stock-data'),
    path('update_stock/<int:stock_id>', views.update_stock, name='update-stock'),
    path('list', views.inventory_list, name='inventory-list'),
    path('list/edit/<int:stock_id>', views.inventory_list_edit,
         name='inventory-list-edit'),
    path('load', views.inventory_load, name='inventory-load'),
    path('export_excel', views.export_excel, name='export-excel'),
    path('po/list', views.inventory_po_list, name='inventory-po-list'),
    path('po/load', views.inventory_po_load, name='inventory-po-load'),
    path('po/list/export_excel', views.po_export_excel, name='po-export-excel'),
    path('po/view/<int:stock_id>', views.po_view, name='po-view'),
    path('po/delete', views.po_delete, name='po-delete'),
    path('stock/locations', views.stock_locations, name='get-stock-locations'),
    path('stock/locations/update', views.update_stock_locations,
         name='update-stock-locations'),
    path('inventory/stock/balance', views.inventory_stock_balance,
         name='inventory-stock-balance'),
    path('out/items/get', views.get_out_items,
         name='get-out-items'),
]
