# Generated by Django 4.2 on 2023-05-07 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('classification', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.brand')),
                ('generic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.generic')),
                ('sub_generic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.subgeneric')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.itemtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.authuser')),
            ],
            options={
                'db_table': 'items',
                'managed': True,
            },
        ),
    ]
