# Generated by Django 4.1.2 on 2023-04-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
